# .github/workflows/gemini-solver.yml
name: Gemini Issue Solver
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  solve-issue:
    runs-on: ubuntu-latest
    # Issueまたはコメントに@gemini/@gptが含まれている場合のみ実行
    if: |
      contains(github.event.issue.body, '@gemini') ||
      contains(github.event.issue.body, '@gemini-pro') ||
      contains(github.event.issue.body, '@gemini-flash') ||
      contains(github.event.issue.body, '@gpt') ||
      contains(github.event.issue.body, '@gpt-o3') ||
      contains(github.event.comment.body, '@gemini') ||
      contains(github.event.comment.body, '@gemini-pro') ||
      contains(github.event.comment.body, '@gemini-flash') ||
      contains(github.event.comment.body, '@gpt') ||
      contains(github.event.comment.body, '@gpt-o3')
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Solve Issue with Gemini
        uses: el-el-san/issue-solver@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          safety-mode: 'normal'
          dry-run: 'false'
          run-tests: 'true'
          # 必要に応じて以下のオプションも設定可能:
          # gemini-model: 'gemini-2.5-pro-preview-06-05'  # 高精度モデルを使用する場合
          # enable-review: 'false'
          # run-linter: 'false'
          # strict-mode: 'false'
          # target-files: 'src/**/*.{js,ts,py}'
          # force-implementation: 'false'
          
          # モデル切り替え例:
          # Geminiモデル:
          # - デフォルト: gemini-2.5-pro-preview-06-05 (高精度)
          # - 高速処理: @gemini-flash または gemini-model: 'gemini-2.5-flash-preview-05-20'
          # - 高精度: @gemini-pro または gemini-model: 'gemini-2.5-pro-preview-06-05'
          # OpenAIモデル:
          # - デフォルト: codex-mini-latest (コスト効率)
          # - 高性能推論: @gpt-o3 (o3-2025-04-16)