name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Build distribution
        run: npm run build
        
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes
            - Bug fixes and improvements
            - See commit history for detailed changes
            
            ## Usage
            ```yaml
            - uses: el-el-san/issue-solver@${{ github.ref }}
              with:
                issue-number: ${{ github.event.issue.number }}
                gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
            ```
          draft: false
          prerelease: false